COMP9517 lab4 20T2\
written by Haowei Lou\
z5258575

In [84]:
from sklearn import metrics
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import multilabel_confusion_matrix
import matplotlib.pyplot as plt
import numpy as np

Set up

In [53]:
digits = load_digits()
x = digits.data
y = digits.target
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25)

In [89]:
def calculate_score(mcm):
    tn = mcm[:, 0, 0]
    tp = mcm[:, 1, 1]
    fn = mcm[:, 1, 0]
    fp = mcm[:, 0, 1]
    recall = tp/(tp+fn)
    recall = recall.sum()/len(recall)
    return recall

KNeighborsClassifier\
The reason for I choose n_neighbors = 3 is because I have looped through n_neighbors = 1 to 100, when n_neighbors = 3, it gives me best accuracy result. And the accuracy result have a trend of decrease as the n_neighbors increase.

In [104]:
for i in range(1,100):
    kneighbors = KNeighborsClassifier(n_neighbors=i)
    kneighbors.fit(x_train,y_train)
    predicted_kn = kneighbors.predict(x_test)
    accuracy_kn = accuracy_score(y_test,predicted_kn)
    recall_kn = calculate_score(multilabel_confusion_matrix(y_test, predicted_kn))
    print("Accuracy is: {0:.2%}".format(accuracy_kn),"Recall is: {0:.2%}".format(recall_kn))

Accuracy is: 98.67% Recall is: 98.68%
Accuracy is: 98.44% Recall is: 98.40%
Accuracy is: 98.44% Recall is: 98.47%
Accuracy is: 97.78% Recall is: 97.69%
Accuracy is: 97.78% Recall is: 97.69%
Accuracy is: 97.78% Recall is: 97.69%
Accuracy is: 97.33% Recall is: 97.27%
Accuracy is: 97.33% Recall is: 97.27%
Accuracy is: 97.33% Recall is: 97.27%
Accuracy is: 97.33% Recall is: 97.31%
Accuracy is: 97.11% Recall is: 97.09%
Accuracy is: 97.11% Recall is: 97.09%
Accuracy is: 97.11% Recall is: 97.09%
Accuracy is: 96.89% Recall is: 96.87%
Accuracy is: 96.89% Recall is: 96.87%
Accuracy is: 96.89% Recall is: 96.87%
Accuracy is: 97.11% Recall is: 97.09%
Accuracy is: 97.11% Recall is: 97.09%
Accuracy is: 97.33% Recall is: 97.31%
Accuracy is: 96.89% Recall is: 96.87%
Accuracy is: 96.89% Recall is: 96.88%
Accuracy is: 96.67% Recall is: 96.66%
Accuracy is: 96.44% Recall is: 96.45%
Accuracy is: 96.22% Recall is: 96.18%
Accuracy is: 96.44% Recall is: 96.45%
Accuracy is: 96.00% Recall is: 95.96%
Accuracy is:

In [105]:
kneighbors = KNeighborsClassifier(n_neighbors=3)
kneighbors.fit(x_train,y_train)
predicted_kn = kneighbors.predict(x_test)
accuracy_kn = accuracy_score(y_test,predicted_kn)
recall_kn = calculate_score(multilabel_confusion_matrix(y_test, predicted_kn))
print("Accuracy is: {0:.2%}".format(accuracy_kn),"Recall is: {0:.2%}".format(recall_kn))

Accuracy is: 98.44% Recall is: 98.47%


SGDClassifier

In [106]:
SGD = SGDClassifier(loss="log", penalty="l2")
SGD.fit(x_train,y_train)
predicted_sgd = SGD.predict(x_test)
accuracy_sgd = accuracy_score(y_test,predicted_sgd)
recall_sgd = calculate_score(multilabel_confusion_matrix(y_test, predicted_sgd))
print("Accuracy is: {0:.2%}".format(accuracy_sgd),"Recall is: {0:.2%}".format(recall_sgd))

Accuracy is: 93.78% Recall is: 93.91%


DecisionTreeClassifier

In [107]:
DTC = DecisionTreeClassifier(random_state=0)
DTC.fit(x_train,y_train)
predicted_DTC = DTC.predict(x_test)
accuracy_DTC = accuracy_score(y_test,predicted_DTC)
recall_dtc = calculate_score(multilabel_confusion_matrix(y_test, predicted_DTC))
print("Accuracy is: {0:.2%}".format(accuracy_DTC),"Recall is: {0:.2%}".format(recall_dtc))

Accuracy is: 85.78% Recall is: 85.87%


Print function

In [108]:
print("COMP9517 Week5 Lab - z5258575\n")
print("Test size = 0.25")
for item1, item2, item3 in zip(["KNN","SGD","DT"],[accuracy_kn,accuracy_sgd,accuracy_DTC],[recall_kn,recall_sgd,recall_dtc]):
    print(item1+" Accuracy: " + "{0:.3}".format(item2) + "     Recall " + "{0:.3}".format(item3))
    
print("\nKNN Confusion Matrix: ")
matrix = confusion_matrix(y_test, predicted_kn)
print(matrix)

COMP9517 Week5 Lab - z5258575

Test size = 0.25
KNN Accuracy: 0.984     Recall 0.985
SGD Accuracy: 0.938     Recall 0.939
DT Accuracy: 0.858     Recall 0.859

KNN Confusion Matrix: 
[[42  0  0  0  0  0  0  0  0  0]
 [ 0 47  0  0  0  0  0  0  0  0]
 [ 0  0 47  0  0  0  0  0  0  0]
 [ 0  0  0 43  0  0  0  1  0  0]
 [ 0  0  0  0 46  0  0  0  0  0]
 [ 0  0  0  0  0 51  0  0  0  2]
 [ 0  0  0  0  0  0 48  0  0  0]
 [ 0  0  0  0  0  0  0 40  0  0]
 [ 0  1  0  0  0  0  0  0 36  0]
 [ 0  1  0  1  0  0  0  0  1 43]]
